package enumeration;

public enum Alimentazione    // TIPO DI DATO IN CUI SI ASSOCIANO DEI VALORI, LIMITANDO LA SCELTA A SOLI QUESTI VALORI
{
	BENZINA,     // QUESTE SONO ETICHETTE, VANNO SEMPRE IN MAIUSCOLO
	DIESEL,
	GPL,
	METANO,
	IBRIDA;

}
