/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Ascensore;

/**
 *
 * @author Marco
 */
public class MasterAscensori extends javax.swing.JFrame {
    Ascensore a1;
    Ascensore a2;
    Ascensore a3;
    /**
     * Creates new form MasterAscensori
     */
    public MasterAscensori() 
    {
        initComponents();
        ArrayList<javax.swing.JButton> ListBtn = new ArrayList();
        ListBtn.add(btnZero);
        ListBtn.add(btnUno);
        ListBtn.add(btnDue);
        ListBtn.add(btnTre);
        ArrayList<javax.swing.JButton> ListBtn2 = new ArrayList();
        ListBtn2.add(btnZero2);
        ListBtn2.add(btnUno2);
        ListBtn2.add(btnDue2);
        ListBtn2.add(btnTre2);
        ArrayList<javax.swing.JButton> ListBtn3 = new ArrayList();
        ListBtn3.add(btnZero3);
        ListBtn3.add(btnUno3);
        ListBtn3.add(btnDue3);
        ListBtn3.add(btnTre3);
        a1 = new Ascensore(0, 1000, lblPiano1, ListBtn, jsAscensore1);
        a2 = new Ascensore(0, 1000, lblPiano2, ListBtn2, jsAscensore2);
        a3 = new Ascensore(0, 1000, lblPiano3, ListBtn3, jsAscensore3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        btnZero = new javax.swing.JButton();
        btnDue = new javax.swing.JButton();
        btnTre = new javax.swing.JButton();
        lblPiano1 = new javax.swing.JLabel();
        btnUno = new javax.swing.JButton();
        lblAscensore1 = new javax.swing.JLabel();
        lblAscensore2 = new javax.swing.JLabel();
        lblPiano2 = new javax.swing.JLabel();
        btnDue2 = new javax.swing.JButton();
        btnUno2 = new javax.swing.JButton();
        btnTre2 = new javax.swing.JButton();
        btnZero2 = new javax.swing.JButton();
        btnDue3 = new javax.swing.JButton();
        btnUno3 = new javax.swing.JButton();
        btnZero3 = new javax.swing.JButton();
        btnTre3 = new javax.swing.JButton();
        lblPiano3 = new javax.swing.JLabel();
        lblAscensore3 = new javax.swing.JLabel();
        jsAscensore2 = new javax.swing.JSlider();
        jsAscensore3 = new javax.swing.JSlider();
        jsAscensore1 = new javax.swing.JSlider();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        btnZero.setText("T");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        desktopPane.add(btnZero);
        btnZero.setBounds(10, 320, 50, 40);

        btnDue.setText("2");
        btnDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueActionPerformed(evt);
            }
        });
        desktopPane.add(btnDue);
        btnDue.setBounds(10, 220, 50, 40);

        btnTre.setText("3");
        btnTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreActionPerformed(evt);
            }
        });
        desktopPane.add(btnTre);
        btnTre.setBounds(10, 170, 50, 40);

        lblPiano1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPiano1.setText("Piano:");
        desktopPane.add(lblPiano1);
        lblPiano1.setBounds(10, 140, 70, 20);

        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        desktopPane.add(btnUno);
        btnUno.setBounds(10, 270, 50, 40);

        lblAscensore1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAscensore1.setText("Ascensore 1");
        desktopPane.add(lblAscensore1);
        lblAscensore1.setBounds(10, 120, 100, 22);

        lblAscensore2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAscensore2.setText("Ascensore 2");
        desktopPane.add(lblAscensore2);
        lblAscensore2.setBounds(260, 120, 100, 22);

        lblPiano2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPiano2.setText("Piano:");
        desktopPane.add(lblPiano2);
        lblPiano2.setBounds(260, 140, 70, 20);

        btnDue2.setText("2");
        btnDue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDue2ActionPerformed(evt);
            }
        });
        desktopPane.add(btnDue2);
        btnDue2.setBounds(260, 220, 50, 40);

        btnUno2.setText("1");
        btnUno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUno2ActionPerformed(evt);
            }
        });
        desktopPane.add(btnUno2);
        btnUno2.setBounds(260, 270, 50, 40);

        btnTre2.setText("3");
        btnTre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTre2ActionPerformed(evt);
            }
        });
        desktopPane.add(btnTre2);
        btnTre2.setBounds(260, 170, 50, 40);

        btnZero2.setText("T");
        btnZero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZero2ActionPerformed(evt);
            }
        });
        desktopPane.add(btnZero2);
        btnZero2.setBounds(260, 320, 50, 40);

        btnDue3.setText("2");
        btnDue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDue3ActionPerformed(evt);
            }
        });
        desktopPane.add(btnDue3);
        btnDue3.setBounds(550, 220, 50, 40);

        btnUno3.setText("1");
        btnUno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUno3ActionPerformed(evt);
            }
        });
        desktopPane.add(btnUno3);
        btnUno3.setBounds(550, 270, 50, 40);

        btnZero3.setText("T");
        btnZero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZero3ActionPerformed(evt);
            }
        });
        desktopPane.add(btnZero3);
        btnZero3.setBounds(550, 320, 50, 40);

        btnTre3.setText("3");
        btnTre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTre3ActionPerformed(evt);
            }
        });
        desktopPane.add(btnTre3);
        btnTre3.setBounds(550, 170, 50, 40);

        lblPiano3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPiano3.setText("Piano:");
        desktopPane.add(lblPiano3);
        lblPiano3.setBounds(550, 140, 70, 20);

        lblAscensore3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAscensore3.setText("Ascensore 3");
        desktopPane.add(lblAscensore3);
        lblAscensore3.setBounds(550, 120, 100, 22);

        jsAscensore2.setMajorTickSpacing(1);
        jsAscensore2.setMaximum(3);
        jsAscensore2.setPaintLabels(true);
        jsAscensore2.setPaintTicks(true);
        jsAscensore2.setSnapToTicks(true);
        desktopPane.add(jsAscensore2);
        jsAscensore2.setBounds(370, 120, 50, 240);

        jsAscensore3.setMajorTickSpacing(1);
        jsAscensore3.setMaximum(3);
        jsAscensore3.setPaintLabels(true);
        jsAscensore3.setPaintTicks(true);
        jsAscensore3.setSnapToTicks(true);
        desktopPane.add(jsAscensore3);
        jsAscensore3.setBounds(660, 120, 50, 240);

        jsAscensore1.setMajorTickSpacing(1);
        jsAscensore1.setMaximum(3);
        jsAscensore1.setPaintLabels(true);
        jsAscensore1.setPaintTicks(true);
        desktopPane.add(jsAscensore1);
        jsAscensore1.setBounds(120, 120, 50, 240);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        a1.setPianoDesiderato(0);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueActionPerformed
        a1.setPianoDesiderato(2);
    }//GEN-LAST:event_btnDueActionPerformed

    private void btnTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreActionPerformed
        a1.setPianoDesiderato(3);
    }//GEN-LAST:event_btnTreActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        a1.setPianoDesiderato(1);
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDue2ActionPerformed
        a2.setPianoDesiderato(2);
    }//GEN-LAST:event_btnDue2ActionPerformed

    private void btnUno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUno2ActionPerformed
       a2.setPianoDesiderato(1);
    }//GEN-LAST:event_btnUno2ActionPerformed

    private void btnTre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTre2ActionPerformed
        a2.setPianoDesiderato(3);
    }//GEN-LAST:event_btnTre2ActionPerformed

    private void btnZero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZero2ActionPerformed
       a2.setPianoDesiderato(0);
    }//GEN-LAST:event_btnZero2ActionPerformed

    private void btnDue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDue3ActionPerformed
        a3.setPianoDesiderato(2);
    }//GEN-LAST:event_btnDue3ActionPerformed

    private void btnUno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUno3ActionPerformed
        a3.setPianoDesiderato(1);
    }//GEN-LAST:event_btnUno3ActionPerformed

    private void btnZero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZero3ActionPerformed
        a3.setPianoDesiderato(0);
    }//GEN-LAST:event_btnZero3ActionPerformed

    private void btnTre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTre3ActionPerformed
        a3.setPianoDesiderato(3);
    }//GEN-LAST:event_btnTre3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterAscensori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterAscensori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterAscensori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterAscensori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterAscensori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDue;
    private javax.swing.JButton btnDue2;
    private javax.swing.JButton btnDue3;
    private javax.swing.JButton btnTre;
    private javax.swing.JButton btnTre2;
    private javax.swing.JButton btnTre3;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnUno2;
    private javax.swing.JButton btnUno3;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btnZero2;
    private javax.swing.JButton btnZero3;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JSlider jsAscensore1;
    private javax.swing.JSlider jsAscensore2;
    private javax.swing.JSlider jsAscensore3;
    private javax.swing.JLabel lblAscensore1;
    private javax.swing.JLabel lblAscensore2;
    private javax.swing.JLabel lblAscensore3;
    private javax.swing.JLabel lblPiano1;
    private javax.swing.JLabel lblPiano2;
    private javax.swing.JLabel lblPiano3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
