/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Alimentazione;
import model.Automobile;
import model.OperazioniAutomobili;

/**
 *
 * @author degennarom
 */
public class AggiornaAuto extends javax.swing.JInternalFrame {
   
    /**
     * Creates new form AggiornaAuto
     */
    public AggiornaAuto() {
        initComponents();
        
        rbBenzina.setActionCommand("Benzina");
        rbDiesel.setActionCommand("Diesel");
        rbGPL.setActionCommand("GPL");
        rbIbrida.setActionCommand("Ibrida");
        rbMetano.setActionCommand("Metano");
        
        txtCilindrata.setEditable(false);
        txtMarca.setEditable(false);
        txtModello.setEditable(false);
        txtColore.setEditable(false);
        btnAggiorna.setEnabled(false);
        rbBenzina.getModel().setEnabled(false);
        rbDiesel.getModel().setEnabled(false);
        rbGPL.getModel().setEnabled(false);
        rbIbrida.getModel().setEnabled(false);
        rbMetano.getModel().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAlimentazione = new javax.swing.ButtonGroup();
        lblAggiornaAuto = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModello = new javax.swing.JLabel();
        txtModello = new javax.swing.JTextField();
        lblCilindrata = new javax.swing.JLabel();
        txtCilindrata = new javax.swing.JTextField();
        lblColore = new javax.swing.JLabel();
        txtColore = new javax.swing.JTextField();
        lblAlimentazione = new javax.swing.JLabel();
        rbBenzina = new javax.swing.JRadioButton();
        rbDiesel = new javax.swing.JRadioButton();
        rbGPL = new javax.swing.JRadioButton();
        rbMetano = new javax.swing.JRadioButton();
        rbIbrida = new javax.swing.JRadioButton();
        btnAggiorna = new javax.swing.JButton();
        lblPosizione = new javax.swing.JLabel();
        txtPosizione = new javax.swing.JTextField();
        btnCerca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(533, 423));

        lblAggiornaAuto.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblAggiornaAuto.setText("Aggiorna Auto");

        lblMarca.setText("Marca:");

        lblModello.setText("Modello:");

        lblCilindrata.setText("Cilindrata:");

        lblColore.setText("Colore:");

        lblAlimentazione.setText("Alimentazione:");

        bgAlimentazione.add(rbBenzina);
        rbBenzina.setText("Benzina");

        bgAlimentazione.add(rbDiesel);
        rbDiesel.setText("Diesel");

        bgAlimentazione.add(rbGPL);
        rbGPL.setText("GPL");

        bgAlimentazione.add(rbMetano);
        rbMetano.setText("Metano");

        bgAlimentazione.add(rbIbrida);
        rbIbrida.setText("Ibrida");

        btnAggiorna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAggiorna.setText("Aggiorna");
        btnAggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiornaActionPerformed(evt);
            }
        });

        lblPosizione.setText("Posizione:");

        txtPosizione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPosizioneMousePressed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca)
                    .addComponent(lblColore)
                    .addComponent(lblAlimentazione)
                    .addComponent(lblModello)
                    .addComponent(lblCilindrata)
                    .addComponent(lblPosizione))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerca))
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAggiornaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBenzina)
                            .addComponent(rbDiesel)
                            .addComponent(rbGPL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMetano)
                            .addComponent(rbIbrida)))
                    .addComponent(btnAggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAggiornaAuto)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosizione)
                    .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModello))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCilindrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColore)
                    .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlimentazione)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbBenzina)
                        .addComponent(rbIbrida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiesel)
                    .addComponent(rbMetano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGPL)
                .addGap(30, 30, 30)
                .addComponent(btnAggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        
        OperazioniAutomobili oa = new OperazioniAutomobili();
        if(oa.IsInt(txtPosizione))
        {
            Automobile aOld = (Automobile)oa.CercaOggettoLista(Integer.parseInt(txtPosizione.getText()));
            if(aOld != null)
            {
                txtCilindrata.setEditable(true);
                txtMarca.setEditable(true);
                txtModello.setEditable(true);
                txtColore.setEditable(true);
                btnAggiorna.setEnabled(true);
                rbBenzina.getModel().setEnabled(true);
                rbDiesel.getModel().setEnabled(true);
                rbGPL.getModel().setEnabled(true);
                rbIbrida.getModel().setEnabled(true);
                rbMetano.getModel().setEnabled(true);
                
                txtMarca.setText(aOld.getMarca());
                txtModello.setText(aOld.getModello());
                txtCilindrata.setText("" + aOld.getCilindrata());
                txtColore.setText(aOld.getColore());

                switch(aOld.getAlimentazione())
                {
                    case BENZINA: 
                         rbBenzina.doClick();
                        break;

                    case DIESEL:
                         rbDiesel.doClick();
                        break;

                    case GPL:
                         rbGPL.doClick();
                        break;

                    case IBRIDA:
                         rbIbrida.doClick();
                        break;

                    case METANO:
                         rbMetano.doClick();
                        break;

                    default:
                        break;
                }
                btnAggiorna.setEnabled(true);
            }
            else
            {
                txtPosizione.setText("");
                JOptionPane.showMessageDialog(null,"Errore!\nNon esiste un'automobile in quella posizione");
            }
        }
        else
        {
            txtPosizione.setText("");
            JOptionPane.showMessageDialog(null,"Errore!\nInserire valore intero in posizione");
        }
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnAggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiornaActionPerformed
        Automobile aNew = new Automobile();
        aNew.setMarca(txtMarca.getText());
        aNew.setModello(txtModello.getText());
        aNew.setColore(txtColore.getText());
        
        switch(bgAlimentazione.getSelection().getActionCommand())
        {
            case "Benzina":
                aNew.setAlimentazione(Alimentazione.BENZINA);
                break;
                
            case "Diesel":
                aNew.setAlimentazione(Alimentazione.DIESEL);
                break;
            
            case "GPL":
                aNew.setAlimentazione(Alimentazione.GPL);
                break;
                
            case "Ibrida":
                aNew.setAlimentazione(Alimentazione.IBRIDA);
                break;
                
            case "Metano":
                aNew.setAlimentazione(Alimentazione.METANO);
                break;
        }
        
        OperazioniAutomobili oa = new OperazioniAutomobili();
        if(oa.IsInt(txtCilindrata))
        {
            aNew.setCilindrata(Integer.parseInt(txtCilindrata.getText()));
            if(oa.VerificaDatiCorretti(aNew))
                oa.ModificaOggettoLista(Integer.parseInt(txtPosizione.getText()), aNew);
            else
                JOptionPane.showMessageDialog(null,"Errore!\nControllare che i campi non siano vuoti\nControllare che la cilindrata sia tra 1000 e 3000");
        }
        else if("".equals(txtCilindrata.getText()))
            JOptionPane.showMessageDialog(null,"Errore! Completare tutti i campi");
        else
            JOptionPane.showMessageDialog(null,"Errore! Inserire valore intero in cilindrata");
    }//GEN-LAST:event_btnAggiornaActionPerformed

    private void txtPosizioneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPosizioneMousePressed
        btnAggiorna.setEnabled(false);
    }//GEN-LAST:event_txtPosizioneMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAlimentazione;
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JButton btnCerca;
    private javax.swing.JLabel lblAggiornaAuto;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModello;
    private javax.swing.JLabel lblPosizione;
    private javax.swing.JRadioButton rbBenzina;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbGPL;
    private javax.swing.JRadioButton rbIbrida;
    private javax.swing.JRadioButton rbMetano;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtColore;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    private javax.swing.JTextField txtPosizione;
    // End of variables declaration//GEN-END:variables
}
