/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author degennarom
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuAutomobili = new javax.swing.JMenu();
        mnuItemNuovo = new javax.swing.JMenuItem();
        mnuItemVisualizza = new javax.swing.JMenuItem();
        mnuItemAggiorna = new javax.swing.JMenuItem();
        mnuItemStampa = new javax.swing.JMenuItem();
        mnuItemElimina = new javax.swing.JMenuItem();
        mnuPersone = new javax.swing.JMenu();
        mnuItemNuovaPersona = new javax.swing.JMenuItem();
        mnuItemVisualizzaPersone = new javax.swing.JMenuItem();
        mnuItemAggiornaPersona = new javax.swing.JMenuItem();
        mnuItemStampaPersona = new javax.swing.JMenuItem();
        mnuItemEliminaPersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 255, 255));

        mnuAutomobili.setText("Automobili");

        mnuItemNuovo.setText("Nuovo");
        mnuItemNuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNuovoActionPerformed(evt);
            }
        });
        mnuAutomobili.add(mnuItemNuovo);

        mnuItemVisualizza.setText("Visualizza");
        mnuItemVisualizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemVisualizzaActionPerformed(evt);
            }
        });
        mnuAutomobili.add(mnuItemVisualizza);

        mnuItemAggiorna.setText("Aggiorna");
        mnuItemAggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAggiornaActionPerformed(evt);
            }
        });
        mnuAutomobili.add(mnuItemAggiorna);

        mnuItemStampa.setText("Stampa");
        mnuItemStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemStampaActionPerformed(evt);
            }
        });
        mnuAutomobili.add(mnuItemStampa);

        mnuItemElimina.setText("Elimina");
        mnuItemElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEliminaActionPerformed(evt);
            }
        });
        mnuAutomobili.add(mnuItemElimina);

        menuBar.add(mnuAutomobili);

        mnuPersone.setText("Persone");

        mnuItemNuovaPersona.setText("Nuovo");
        mnuItemNuovaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNuovaPersonaActionPerformed(evt);
            }
        });
        mnuPersone.add(mnuItemNuovaPersona);

        mnuItemVisualizzaPersone.setText("Visualizza");
        mnuItemVisualizzaPersone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemVisualizzaPersoneActionPerformed(evt);
            }
        });
        mnuPersone.add(mnuItemVisualizzaPersone);

        mnuItemAggiornaPersona.setText("Aggiorna");
        mnuItemAggiornaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAggiornaPersonaActionPerformed(evt);
            }
        });
        mnuPersone.add(mnuItemAggiornaPersona);

        mnuItemStampaPersona.setText("Stampa");
        mnuItemStampaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemStampaPersonaActionPerformed(evt);
            }
        });
        mnuPersone.add(mnuItemStampaPersona);

        mnuItemEliminaPersona.setText("Elimina");
        mnuItemEliminaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEliminaPersonaActionPerformed(evt);
            }
        });
        mnuPersone.add(mnuItemEliminaPersona);

        menuBar.add(mnuPersone);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemNuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNuovoActionPerformed
        NuovaAuto na = new NuovaAuto();
        na.setVisible(true);
        this.desktopPane.add(na);
    }//GEN-LAST:event_mnuItemNuovoActionPerformed
    
    private void mnuItemVisualizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemVisualizzaActionPerformed
        VisualizzaAuto va = new VisualizzaAuto();
        va.setVisible(true);
        this.desktopPane.add(va);
    }//GEN-LAST:event_mnuItemVisualizzaActionPerformed

    private void mnuItemAggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAggiornaActionPerformed
        AggiornaAuto aa = new AggiornaAuto();
        aa.setVisible(true);
        this.desktopPane.add(aa);
    }//GEN-LAST:event_mnuItemAggiornaActionPerformed

    private void mnuItemStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemStampaActionPerformed
        StampaAuto sa = new StampaAuto();
        sa.setVisible(true);
        this.desktopPane.add(sa);
    }//GEN-LAST:event_mnuItemStampaActionPerformed

    private void mnuItemEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEliminaActionPerformed
        EliminaAuto ea = new EliminaAuto();
        ea.setVisible(true);
        this.desktopPane.add(ea);
    }//GEN-LAST:event_mnuItemEliminaActionPerformed

    private void mnuItemNuovaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNuovaPersonaActionPerformed
        NuovaPersona np = new NuovaPersona();
        np.setVisible(true);
        this.desktopPane.add(np);
    }//GEN-LAST:event_mnuItemNuovaPersonaActionPerformed

    private void mnuItemVisualizzaPersoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemVisualizzaPersoneActionPerformed
        VisualizzaPersone vp = new VisualizzaPersone();
        vp.setVisible(true);
        this.desktopPane.add(vp);
    }//GEN-LAST:event_mnuItemVisualizzaPersoneActionPerformed

    private void mnuItemAggiornaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAggiornaPersonaActionPerformed
        AggiornaPersona ap = new AggiornaPersona();
        ap.setVisible(true);
        this.desktopPane.add(ap);
    }//GEN-LAST:event_mnuItemAggiornaPersonaActionPerformed

    private void mnuItemStampaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemStampaPersonaActionPerformed
        StampaPersona sp = new StampaPersona();
        sp.setVisible(true);
        this.desktopPane.add(sp);
    }//GEN-LAST:event_mnuItemStampaPersonaActionPerformed

    private void mnuItemEliminaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEliminaPersonaActionPerformed
        EliminaPersona ep = new EliminaPersona();
        ep.setVisible(true);
        this.desktopPane.add(ep);
    }//GEN-LAST:event_mnuItemEliminaPersonaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAutomobili;
    private javax.swing.JMenuItem mnuItemAggiorna;
    private javax.swing.JMenuItem mnuItemAggiornaPersona;
    private javax.swing.JMenuItem mnuItemElimina;
    private javax.swing.JMenuItem mnuItemEliminaPersona;
    private javax.swing.JMenuItem mnuItemNuovaPersona;
    private javax.swing.JMenuItem mnuItemNuovo;
    private javax.swing.JMenuItem mnuItemStampa;
    private javax.swing.JMenuItem mnuItemStampaPersona;
    private javax.swing.JMenuItem mnuItemVisualizza;
    private javax.swing.JMenuItem mnuItemVisualizzaPersone;
    private javax.swing.JMenu mnuPersone;
    // End of variables declaration//GEN-END:variables

}
