/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import model.OperazioniPersone;
import model.Persona;
import model.Sesso;

/**
 *
 * @author Marco
 */
public class NuovaPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuovaPersona
     */
    public NuovaPersona() {
        initComponents();
        rbMaschio.setActionCommand("Maschio");
        rbFemmina.setActionCommand("Femmina");
        rbAltro.setActionCommand("Altro");
        rbMaschio.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSesso = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        txtLuogoNascita = new javax.swing.JTextField();
        lblAggiungiPersona = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        rbMaschio = new javax.swing.JRadioButton();
        lblCognome = new javax.swing.JLabel();
        rbFemmina = new javax.swing.JRadioButton();
        lblDataNascita = new javax.swing.JLabel();
        rbAltro = new javax.swing.JRadioButton();
        lblLuogoNascita = new javax.swing.JLabel();
        lblSesso = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        txtDataNascita = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblAggiungiPersona.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblAggiungiPersona.setText("Aggiungi persona");

        btnSalva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalva.setText("Salva");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        bgSesso.add(rbMaschio);
        rbMaschio.setText("Maschio");

        lblCognome.setText("Cognome:");

        bgSesso.add(rbFemmina);
        rbFemmina.setText("Femmina");

        lblDataNascita.setText("Data Nascita:");

        bgSesso.add(rbAltro);
        rbAltro.setText("Altro");

        lblLuogoNascita.setText("Luogo Nascita:");

        lblSesso.setText("Sesso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblAggiungiPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblCognome)
                            .addComponent(lblDataNascita)
                            .addComponent(lblLuogoNascita)
                            .addComponent(lblSesso))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFemmina)
                            .addComponent(rbAltro)
                            .addComponent(btnSalva)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLuogoNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rbMaschio))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAggiungiPersona)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCognome)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascita)
                    .addComponent(txtDataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuogoNascita)
                    .addComponent(txtLuogoNascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMaschio)
                    .addComponent(lblSesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFemmina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAltro)
                .addGap(18, 18, 18)
                .addComponent(btnSalva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed

        Persona pNew = new Persona();
        pNew.setNome(txtNome.getText());
        pNew.setCognome(txtCognome.getText());
        pNew.setLuogoNascita(txtLuogoNascita.getText());

        switch(bgSesso.getSelection().getActionCommand())
        {
            case "Maschio":
            pNew.setSesso(Sesso.MASCHIO);
            break;

            case "Femmina":
            pNew.setSesso(Sesso.FEMMINA);
            break;

            case "Altro":
            pNew.setSesso(Sesso.ALTRO);
            break;
        }
        OperazioniPersone op = new OperazioniPersone();
        if(op.IsDateFormat(txtDataNascita))
        {
            String[] data = txtDataNascita.getText().split("/");
            int [] dataInt = op.ParserizzaData(data);
            GregorianCalendar dataNascita = new GregorianCalendar(dataInt[0], dataInt[1]-1, dataInt[2]);
            pNew.setDataNascita(dataNascita);
            if(op.VerificaDatiCorretti(pNew))
                op.AggiungiOggettoLista(pNew);
            else
                JOptionPane.showMessageDialog(null,"Errore!\nControllare che i campi non siano vuoti\nControllare il formato della data");
        }
        else if("".equals(txtDataNascita.getText()))
            JOptionPane.showMessageDialog(null,"Errore! Completare tutti i campi");
        else
            JOptionPane.showMessageDialog(null,"Errore! Formato della data deve essere il seguente: 01/01/2000");
    }//GEN-LAST:event_btnSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSesso;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel lblAggiungiPersona;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblDataNascita;
    private javax.swing.JLabel lblLuogoNascita;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSesso;
    private javax.swing.JRadioButton rbAltro;
    private javax.swing.JRadioButton rbFemmina;
    private javax.swing.JRadioButton rbMaschio;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtDataNascita;
    private javax.swing.JTextField txtLuogoNascita;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
