/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.awt.image.ImageObserver.WIDTH;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import model.OperazioniPersone;
import model.Persona;

/**
 *
 * @author degennarom
 */
public class EliminaPersona extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form EliminaAuto
     */
    public EliminaPersona() {
        initComponents();
        txtNome.setEditable(false);
        txtCognome.setEditable(false);
        txtDataNascita.setEditable(false);
        txtLuogoNascita.setEditable(false);
        rbMaschio.getModel().setEnabled(false);
        rbFemmina.getModel().setEnabled(false);
        rbAltro.getModel().setEnabled(false);
        btnElimina.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSesso = new javax.swing.ButtonGroup();
        txtLuogoNascita = new javax.swing.JTextField();
        rbMaschio = new javax.swing.JRadioButton();
        lblSesso = new javax.swing.JLabel();
        rbFemmina = new javax.swing.JRadioButton();
        txtCognome = new javax.swing.JTextField();
        rbAltro = new javax.swing.JRadioButton();
        txtDataNascita = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        lblEliminaPersona = new javax.swing.JLabel();
        lblDataNascita = new javax.swing.JLabel();
        txtPosizione = new javax.swing.JTextField();
        lblLuogoNascita = new javax.swing.JLabel();
        lblPosizione = new javax.swing.JLabel();
        btnCerca = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        bgSesso.add(rbMaschio);
        rbMaschio.setText("Maschio");

        lblSesso.setText("Sesso:");

        bgSesso.add(rbFemmina);
        rbFemmina.setText("Femmina");

        bgSesso.add(rbAltro);
        rbAltro.setText("Altro");

        lblNome.setText("Nome:");

        lblCognome.setText("Cognome:");

        lblEliminaPersona.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblEliminaPersona.setText("Elimina persona");

        lblDataNascita.setText("Data Nascita:");

        txtPosizione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPosizioneMousePressed(evt);
            }
        });

        lblLuogoNascita.setText("Luogo Nascita:");

        lblPosizione.setText("Posizione:");

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblEliminaPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCognome)
                            .addComponent(lblNome)
                            .addComponent(lblDataNascita)
                            .addComponent(lblLuogoNascita)
                            .addComponent(lblSesso)
                            .addComponent(lblPosizione))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCognome)
                            .addComponent(txtNome)
                            .addComponent(txtDataNascita)
                            .addComponent(txtLuogoNascita)
                            .addComponent(rbMaschio)
                            .addComponent(rbFemmina)
                            .addComponent(rbAltro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerca))
                            .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEliminaPersona)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosizione)
                    .addComponent(btnCerca))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCognome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuogoNascita)
                    .addComponent(txtLuogoNascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSesso)
                    .addComponent(rbMaschio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFemmina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPosizioneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPosizioneMousePressed
        btnElimina.setEnabled(false);
    }//GEN-LAST:event_txtPosizioneMousePressed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed

        OperazioniPersone op = new OperazioniPersone();
        if(op.IsInt(txtPosizione))
        {
            Persona pOld = (Persona)op.CercaOggettoLista(Integer.parseInt(txtPosizione.getText()));
            if(pOld != null)
            {
                txtNome.setText(pOld.getNome());
                txtCognome.setText(pOld.getCognome());
                GregorianCalendar dataNascita = pOld.getDataNascita();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                txtDataNascita.setText(sdf.format(dataNascita.getTime()));
                txtLuogoNascita.setText(pOld.getLuogoNascita());

                switch(pOld.getSesso())
                {
                    case MASCHIO: 
                        rbMaschio.setEnabled(true);
                        rbMaschio.doClick();
                        rbMaschio.setEnabled(false);
                        break;

                    case FEMMINA:
                        rbFemmina.setEnabled(true);
                        rbFemmina.doClick();
                        rbFemmina.setEnabled(false);
                        break;

                    case ALTRO:
                        rbAltro.setEnabled(true);
                        rbAltro.doClick();
                        rbAltro.setEnabled(false);
                        break;
                }
                btnElimina.setEnabled(true);
            }
            else
            {
                txtPosizione.setText("");
                JOptionPane.showMessageDialog(null,"Errore!\nNon esiste una persona in quella posizione");
            }
        }
        else
        {
            txtPosizione.setText("");
            JOptionPane.showMessageDialog(null,"Errore!\nInserire valore intero in posizione");
        }
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
    if(JOptionPane.showConfirmDialog(rootPane, "Sei sicuro di voler eliminare la persona richiesta?", "Eliminazione", WIDTH) == 0)
    {    
        OperazioniPersone op = new OperazioniPersone();
        op.EliminaOggettoLista(Integer.parseInt(txtPosizione.getText()));
        txtNome.setText("");
        txtCognome.setText("");
        txtDataNascita.setText("");
        txtLuogoNascita.setText("");
        txtPosizione.setText("");
        bgSesso.clearSelection();
        JOptionPane.showMessageDialog(null,"Dati eliminati con successo!");
        btnElimina.setEnabled(false);
    }
    }//GEN-LAST:event_btnEliminaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSesso;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblDataNascita;
    private javax.swing.JLabel lblEliminaPersona;
    private javax.swing.JLabel lblLuogoNascita;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPosizione;
    private javax.swing.JLabel lblSesso;
    private javax.swing.JRadioButton rbAltro;
    private javax.swing.JRadioButton rbFemmina;
    private javax.swing.JRadioButton rbMaschio;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtDataNascita;
    private javax.swing.JTextField txtLuogoNascita;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPosizione;
    // End of variables declaration//GEN-END:variables
}
