/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Automobile;
import model.Alimentazione;
import model.OperazioniAutomobili;

/**
 *
 * @author degennarom
 */
public class NuovaAuto extends javax.swing.JInternalFrame {
    
    //private String path = "auto.dat";
    /**
     * Creates new form NuovaAuto
     */
    public NuovaAuto() {
        initComponents();
        //Inizializzo i radiobutton lasciando rbBenzina selezionato di default
        txtCilindrata.setText("");
        rbBenzina.setActionCommand("Benzina");
        rbDiesel.setActionCommand("Diesel");
        rbGPL.setActionCommand("GPL");
        rbIbrida.setActionCommand("Ibrida");
        rbMetano.setActionCommand("Metano");
        rbBenzina.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAlimentazione = new javax.swing.ButtonGroup();
        lblNuovaAuto = new javax.swing.JLabel();
        lblCilindrata = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModello = new javax.swing.JLabel();
        lblColore = new javax.swing.JLabel();
        lblAlimentazione = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        txtCilindrata = new javax.swing.JTextField();
        txtColore = new javax.swing.JTextField();
        btnSalva = new javax.swing.JButton();
        rbBenzina = new javax.swing.JRadioButton();
        rbDiesel = new javax.swing.JRadioButton();
        rbGPL = new javax.swing.JRadioButton();
        rbIbrida = new javax.swing.JRadioButton();
        rbMetano = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(533, 423));

        lblNuovaAuto.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblNuovaAuto.setText("Nuova Auto");

        lblCilindrata.setText("Cilindrata:");

        lblMarca.setText("Marca:");

        lblModello.setText("Modello:");

        lblColore.setText("Colore:");

        lblAlimentazione.setText("Alimentazione:");

        btnSalva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalva.setText("Salva");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        bgAlimentazione.add(rbBenzina);
        rbBenzina.setText("Benzina");

        bgAlimentazione.add(rbDiesel);
        rbDiesel.setText("Diesel");

        bgAlimentazione.add(rbGPL);
        rbGPL.setText("GPL");

        bgAlimentazione.add(rbIbrida);
        rbIbrida.setText("Ibrida");

        bgAlimentazione.add(rbMetano);
        rbMetano.setText("Metano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca)
                    .addComponent(lblColore)
                    .addComponent(lblAlimentazione)
                    .addComponent(lblModello)
                    .addComponent(lblCilindrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMarca)
                    .addComponent(txtModello)
                    .addComponent(txtCilindrata)
                    .addComponent(txtColore)
                    .addComponent(rbGPL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBenzina)
                            .addComponent(rbDiesel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMetano)
                            .addComponent(rbIbrida)))
                    .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuovaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNuovaAuto)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModello))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCilindrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColore)
                    .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlimentazione)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbBenzina)
                        .addComponent(rbIbrida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiesel)
                    .addComponent(rbMetano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGPL)
                .addGap(34, 34, 34)
                .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        
        Automobile aNew = new Automobile();
        aNew.setMarca(txtMarca.getText());
        aNew.setModello(txtModello.getText());
        aNew.setColore(txtColore.getText());
        
        switch(bgAlimentazione.getSelection().getActionCommand())
        {
            case "Benzina":
                aNew.setAlimentazione(Alimentazione.BENZINA);
                break;
                
            case "Diesel":
                aNew.setAlimentazione(Alimentazione.DIESEL);
                break;
            
            case "GPL":
                aNew.setAlimentazione(Alimentazione.GPL);
                break;
                
            case "Ibrida":
                aNew.setAlimentazione(Alimentazione.IBRIDA);
                break;
                
            case "Metano":
                aNew.setAlimentazione(Alimentazione.METANO);
                break;
        }
        
        /*istanzio un oggetti di tipo OperazioniAutomobili che dovrà operare per aggiungere una nuova auto nella lista con
          salvataggio sul file.dat*/
        OperazioniAutomobili oa = new OperazioniAutomobili();
        if(oa.IsInt(txtCilindrata))
        {
            aNew.setCilindrata(Integer.parseInt(txtCilindrata.getText()));
            if(oa.VerificaDatiCorretti(aNew))
                oa.AggiungiOggettoLista(aNew);
            else
                JOptionPane.showMessageDialog(null,"Errore!\nControllare che i campi non siano vuoti\nControllare che la cilindrata sia tra 1000 e 3000");
        }
        else if("".equals(txtCilindrata.getText()))
            JOptionPane.showMessageDialog(null,"Errore! Completare tutti i campi");
        else
            JOptionPane.showMessageDialog(null,"Errore! Inserire valore intero in cilindrata");
    }//GEN-LAST:event_btnSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAlimentazione;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModello;
    private javax.swing.JLabel lblNuovaAuto;
    private javax.swing.JRadioButton rbBenzina;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbGPL;
    private javax.swing.JRadioButton rbIbrida;
    private javax.swing.JRadioButton rbMetano;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtColore;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    // End of variables declaration//GEN-END:variables
}
