/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Computer;
import model.MyLibrary;
import model.Prodotto;

/**
 *
 * @author Marco de Gennaro 16/05/2017 Integrated Backend Services
 */
public class ConfiguraComputer extends javax.swing.JInternalFrame {
    
    ArrayList<Prodotto> prodotti;
    /**
     * Creates new form ConfiguraComputer
     */
    public ConfiguraComputer() {
    initComponents();
    cbProcessore.removeAllItems();
    cbMemoria.removeAllItems();
    cbHardDisk.removeAllItems();
    cbTastiera.removeAllItems();
    cbMonitor.removeAllItems();
    cbMouse.removeAllItems();
    prodotti = MyLibrary.LeggiFileTesto("database.csv");

    for(Prodotto p : prodotti)
    {
        switch(p.getCategoria())
        {
            case "processore":
                cbProcessore.addItem(p.getNome());
                break;

            case "monitor":
                cbMonitor.addItem(p.getNome());
                break;

            case "tastiera":
                cbTastiera.addItem(p.getNome());
                break;

            case "memoria":
                cbMemoria.addItem(p.getNome());
                break;

            case "hard-disk":
                cbHardDisk.addItem(p.getNome());
                break;
                
            case "mouse":
                cbMouse.addItem(p.getNome());
                break;
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcessore = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        lblHardDisk = new javax.swing.JLabel();
        lblMonitor = new javax.swing.JLabel();
        lblTastiera = new javax.swing.JLabel();
        cbProcessore = new javax.swing.JComboBox<>();
        cbMemoria = new javax.swing.JComboBox<>();
        cbTastiera = new javax.swing.JComboBox<>();
        cbHardDisk = new javax.swing.JComboBox<>();
        cbMonitor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnConfigura = new javax.swing.JButton();
        lblMouse = new javax.swing.JLabel();
        cbMouse = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblProcessore.setText("Processore:");

        lblMemoria.setText("Memoria:");

        lblHardDisk.setText("Hard disk:");

        lblMonitor.setText("Monitor:");

        lblTastiera.setText("Tastiera:");

        cbProcessore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTastiera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbHardDisk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Configura Computer");

        btnConfigura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfigura.setText("Configura");
        btnConfigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguraActionPerformed(evt);
            }
        });

        lblMouse.setText("Mouse:");

        cbMouse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfigura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMemoria)
                                    .addComponent(lblHardDisk)
                                    .addComponent(lblMonitor)
                                    .addComponent(lblTastiera)
                                    .addComponent(lblMouse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMonitor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHardDisk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMemoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTastiera, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProcessore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProcessore, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcessore)
                    .addComponent(cbProcessore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemoria)
                    .addComponent(cbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHardDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHardDisk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonitor)
                    .addComponent(cbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTastiera)
                    .addComponent(cbTastiera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMouse)
                    .addComponent(cbMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnConfigura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguraActionPerformed
        Computer pc = new Computer();
        
        for(Prodotto p : prodotti)
        {
            if(cbProcessore.getSelectedItem().toString() == p.getNome())
                pc.setProcessore(p);
            
            if(cbMonitor.getSelectedItem().toString() == p.getNome())
                pc.setMonitor(p);
            
            if(cbTastiera.getSelectedItem().toString() == p.getNome())
                pc.setTastiera(p);
            
            if(cbMouse.getSelectedItem().toString() == p.getNome())
                pc.setMouse(p);
            
            if(cbMemoria.getSelectedItem().toString() == p.getNome())
                pc.setMemoria(p);
            
            if(cbHardDisk.getSelectedItem().toString() == p.getNome())
                pc.setHardDisk(p);
        }
        DatiComputerCustom dcp = new DatiComputerCustom(pc);
        dcp.setVisible(true);
    }//GEN-LAST:event_btnConfiguraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigura;
    private javax.swing.JComboBox<String> cbHardDisk;
    private javax.swing.JComboBox<String> cbMemoria;
    private javax.swing.JComboBox<String> cbMonitor;
    private javax.swing.JComboBox<String> cbMouse;
    private javax.swing.JComboBox<String> cbProcessore;
    private javax.swing.JComboBox<String> cbTastiera;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblHardDisk;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMonitor;
    private javax.swing.JLabel lblMouse;
    private javax.swing.JLabel lblProcessore;
    private javax.swing.JLabel lblTastiera;
    // End of variables declaration//GEN-END:variables
}
