/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Automobile;
import model.MyLibrary;

/**
 *
 * @author degennarom
 */
public class EliminaAuto extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminaAuto
     */
    public EliminaAuto() {
        initComponents();
        rbBenzina.setActionCommand("Benzina");
        rbDiesel.setActionCommand("Diesel");
        rbGPL.setActionCommand("GPL");
        rbIbrida.setActionCommand("Ibrida");
        rbMetano.setActionCommand("Metano");
        
        txtCilindrata.setEditable(false);
        txtMarca.setEditable(false);
        txtModello.setEditable(false);
        txtColore.setEditable(false);
        rbBenzina.getModel().setEnabled(false);
        rbDiesel.getModel().setEnabled(false);
        rbGPL.getModel().setEnabled(false);
        rbIbrida.getModel().setEnabled(false);
        rbMetano.getModel().setEnabled(false);
        btnElimina.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAlimentazione = new javax.swing.ButtonGroup();
        lblCilindrata = new javax.swing.JLabel();
        txtCilindrata = new javax.swing.JTextField();
        lblPosizione = new javax.swing.JLabel();
        lblColore = new javax.swing.JLabel();
        txtPosizione = new javax.swing.JTextField();
        txtColore = new javax.swing.JTextField();
        btnCerca = new javax.swing.JButton();
        lblAlimentazione = new javax.swing.JLabel();
        rbBenzina = new javax.swing.JRadioButton();
        lblEliminaAuto = new javax.swing.JLabel();
        rbDiesel = new javax.swing.JRadioButton();
        lblMarca = new javax.swing.JLabel();
        rbGPL = new javax.swing.JRadioButton();
        txtMarca = new javax.swing.JTextField();
        rbMetano = new javax.swing.JRadioButton();
        lblModello = new javax.swing.JLabel();
        rbIbrida = new javax.swing.JRadioButton();
        txtModello = new javax.swing.JTextField();
        btnElimina = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblCilindrata.setText("Cilindrata:");

        lblPosizione.setText("Posizione:");

        lblColore.setText("Colore:");

        txtPosizione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPosizioneMousePressed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        lblAlimentazione.setText("Alimentazione:");

        bgAlimentazione.add(rbBenzina);
        rbBenzina.setText("Benzina");

        lblEliminaAuto.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblEliminaAuto.setText("Elimina Auto");

        bgAlimentazione.add(rbDiesel);
        rbDiesel.setText("Diesel");

        lblMarca.setText("Marca:");

        bgAlimentazione.add(rbGPL);
        rbGPL.setText("GPL");

        bgAlimentazione.add(rbMetano);
        rbMetano.setText("Metano");

        lblModello.setText("Modello:");

        bgAlimentazione.add(rbIbrida);
        rbIbrida.setText("Ibrida");

        btnElimina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca)
                    .addComponent(lblColore)
                    .addComponent(lblAlimentazione)
                    .addComponent(lblModello)
                    .addComponent(lblCilindrata)
                    .addComponent(lblPosizione))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBenzina)
                            .addComponent(rbDiesel)
                            .addComponent(rbGPL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbIbrida)
                            .addComponent(rbMetano)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerca))
                            .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEliminaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblEliminaAuto)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosizione)
                    .addComponent(txtPosizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModello))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCilindrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColore)
                    .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlimentazione)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbBenzina)
                        .addComponent(rbIbrida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiesel)
                    .addComponent(rbMetano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGPL)
                .addGap(34, 34, 34)
                .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed

        ArrayList<Automobile> automobili = MyLibrary.LeggiFile();
        if(MyLibrary.VerificaPosizione(txtPosizione, automobili))
        {
            Automobile a = automobili.get(Integer.parseInt(txtPosizione.getText()));

            txtMarca.setText(a.getMarca());
            txtModello.setText(a.getModello());
            txtCilindrata.setText("" + a.getCilindrata());
            txtColore.setText(a.getColore());

            switch(a.getAlimentazione())
            {
                case BENZINA:
                    rbBenzina.setEnabled(true);
                    rbBenzina.doClick();
                    rbBenzina.setEnabled(false);
                break;

                case DIESEL:
                    rbDiesel.setEnabled(true);
                    rbDiesel.doClick();
                    rbDiesel.setEnabled(false);
                    break;

                case GPL:
                    rbGPL.setEnabled(true);
                    rbGPL.doClick();
                    rbGPL.setEnabled(false);
                    break;

                case IBRIDA:
                    rbIbrida.setEnabled(true);
                    rbIbrida.doClick();
                    rbIbrida.setEnabled(false);
                    break;

                case METANO:
                    rbMetano.setEnabled(true);
                    rbMetano.doClick();
                    rbMetano.setEnabled(false);
                    break;

                default:
                    break;
            }
            btnElimina.setEnabled(true);
        }
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        ArrayList<Automobile> automobili = MyLibrary.LeggiFile();
        int index = Integer.parseInt(txtPosizione.getText());
        automobili.remove(index);
        MyLibrary.ScriviFile(automobili);
        txtMarca.setText("");
        txtModello.setText("");
        txtCilindrata.setText("");
        txtColore.setText("");
        txtPosizione.setText("");
        bgAlimentazione.clearSelection();
        JOptionPane.showMessageDialog(null,"Dati eliminati con successo");
        btnElimina.setEnabled(false);
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void txtPosizioneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPosizioneMousePressed
      btnElimina.setEnabled(false);
    }//GEN-LAST:event_txtPosizioneMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAlimentazione;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblEliminaAuto;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModello;
    private javax.swing.JLabel lblPosizione;
    private javax.swing.JRadioButton rbBenzina;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbGPL;
    private javax.swing.JRadioButton rbIbrida;
    private javax.swing.JRadioButton rbMetano;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtColore;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    private javax.swing.JTextField txtPosizione;
    // End of variables declaration//GEN-END:variables
}
